sudo: false
language: c

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - |
    set -ex
    stack --no-terminal --install-ghc build --only-dependencies
    set +ex

script:
  - |
    set -ex
    stack --no-terminal build
    stack --no-terminal exec site rebuild
    set +ex
