sudo: false
dist: trusty
language: generic
addons:
  apt:
    update: true
    packages:
      - libgmp-dev
cache:
  directories:
    - "$HOME/.stack"

git:
  lfs_skip_smudge: true

env:
  global:
    - secure: "kwp7vp00zCoQruHH2xE7cQRxa2Fga8OyoJAXiEOTtHxu68IU9tZIxVKt9w2ngFtgXKc9KnxQ6DC0l9xrqIaJWFMobHuZx8PWqgQuSq99/qTprZPpyYjgM+HFJJKs3w4PDSboDPRGX49hnOwTMY60piZWOn6rZcuUELYmAFfjy0U="
    - secure: "gHW8hrYrK6fM8ucosiQ6fmvnb5l32128yoxsK5i/BZ4gSmSo/55E11OpKlLfjrDW1WDlVuQg1+nsritsqMcihe8fY1y56NZyJP01tYSFedcmdSL8QMwyQkmqbB3wnuGVWU/soALOfWyw4VTkXLHi/5tyGOwqsPcXnjnWvpjnuks="
    - secure: "TOQGiqs1uB5iYjxk6qHbIKSpWZoh8PFkBp8IXbX3x7nrVFCa0+yCpNV8XOaIZwvEPRm5DTYbFTCIFNRHimGCdaSxJ9wqJMbSEWhEg7dC2mbwmIIsx2ugEsjuFAJgJjknd8B/d6SDk9NtlQFMaxVTM3c2kS6i3KyaUrnM/aW1NCo="

before_install:
  - git lfs install
  - openssl aes-256-cbc -K $encrypted_64b0588f674e_key -iv $encrypted_64b0588f674e_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - chmod 600 .travis/id_rsa
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack -j2 --no-terminal setup
  - stack -j2 --no-terminal build --only-dependencies

before_script:
  - git lfs pull

script:
  - stack -j2 --no-terminal build
  - stack -j2 --no-terminal exec site rebuild

after_success:
  - eval "$(ssh-agent -s)"
  - ssh-add .travis/id_rsa
  - rsync --delete -qurt -e "ssh -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p $DEPLOY_PORT -l travis" _site/ $DEPLOY_HOST:gekkio.fi/ > /dev/null 2>&1
  - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p $DEPLOY_PORT -l travis $DEPLOY_HOST ./deploy_site.sh > /dev/null 2>&1
